set windows-shell := ["nu.exe", "-c"]

default:
    @just --list --unsorted

build:
    cargo build --release

lint:
    cargo clippy --all-targets --all-features -- -D warnings

fmt:
    cargo fmt --all

test:
    cargo test --all-features

check:
    cargo check --all-targets --all-features

run WOW_DIR OUT_DIR:
    cargo run --release -- --data-dir "{{WOW_DIR}}" --output "{{OUT_DIR}}" --format json
